services:
  - docker:stable-dind

variables:
  IMAGE: $CI_REGISTRY_IMAGE:latest
  BUILDER: $CI_REGISTRY_IMAGE:builder

stages:
  - gitlab
  - unit
  - build

gitlab-builder:
  image: docker:stable
  stage: gitlab
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - apk add --update make

    - make devel BUILDER=$BUILDER
    - docker push $BUILDER

unit-tests:
  stage: unit
  image: $BUILDER
  script:
    - make verify

build-image:
  stage: build
  image: docker:stable
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - apk add --update make

    - make image IMAGE=$IMAGE
    - docker push $IMAGE
