variables:
  DOCKERHUB: nvidia/gpu-operator
  NVCRIO: nvcr.io/nvstaging/cloud-native/gpu-operator
  TF_VAR_FILE: "$CI_PROJECT_DIR/tests/terraform.tfvars"

# Ensure the @OPERATOR_VERSION@ is rewritten before any action is taken
default:
  before_script:
    - CI_COMMIT_TAG=${CI_COMMIT_TAG:-"${CI_COMMIT_SHA}"}
    - sed -i "s/@OPERATOR_VERSION@/${CI_COMMIT_TAG}/" $(find ./deployments/gpu-operator -type f)

stages:
  - gitlab
  - unit
  - build
  - aws_kube_setup
  - e2e_tests
  - aws_kube_clean
  - release

gitlab-builder:
  image: docker:stable
  stage: gitlab
  services:
    - docker:stable-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - apk add --update make

    - make devel BUILDER=$CI_REGISTRY_IMAGE:builder
    - docker push $CI_REGISTRY_IMAGE:builder

unit-tests:
  stage: unit
  image: $CI_REGISTRY_IMAGE:builder
  script:
    - make verify

build-image:
  stage: build
  image: docker:stable
  services:
    - docker:stable-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - apk add --update make

    - make image IMAGE=$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

e2e_tests:
  stage: e2e_tests
  image: alpine
  script:
    - source aws-kube-ci/hostname
    - apk add --no-cache openssh-client rsync
    - rsync -e "ssh -i aws-kube-ci/key -o StrictHostKeyChecking=no" -av --exclude="vendor/" "${CI_PROJECT_DIR}" "${instance_hostname}:~/"
    - rc=0
    - (ssh -i aws-kube-ci/key -o StrictHostKeyChecking=no ${instance_hostname} "cd ~/gpu-operator/tests && ./ci-run-e2e.sh ${CI_REGISTRY_IMAGE} ${CI_COMMIT_SHA}") || rc=$?
    - rsync -e "ssh -i aws-kube-ci/key" -av "${instance_hostname}:/tmp/logs/" logs
    - exit $rc
  dependencies:
    - aws_kube_setup
  artifacts:
    when: always
    paths:
      - logs/

include:
  project: nvidia/container-infrastructure/aws-kube-ci
  file: aws-kube-ci.yml

release-containers:
  stage: release
  image: docker:stable
  only:
    - tags # Only when a protected tag is pushed

  script:
    - docker login -u "${REGISTRY_USER}" -p "${REGISTRY_TOKEN}"
    - docker login -u "${NVCRIO_USER}" -p "${NVCRIO_TOKEN}"

    - apk add --update make

    - make image IMAGE="${DOCKERHUB}:${CI_COMMIT_TAG}"
    - docker push "${DOCKERHUB}:${CI_COMMIT_TAG}"

    - make image IMAGE="${NVCRIO}:${CI_COMMIT_TAG}"
    - docker push "${NVCRIO}:${CI_COMMIT_TAG}"

release-helm:
  image: alpine:latest
  stage: release # Should be after each successful commit
  variables:
    GIT_STRATEGY: clone
  only:
    - master

  script:
    - apk add --update curl openssl bash git openssh
    - curl -L https://git.io/get_helm.sh | bash
    - mkdir ~/.ssh && echo "$PRIVATE_SSH_KEY" &> ~/.ssh/id_rsa && chmod 0600 ~/.ssh/id_rsa
    - git config --global user.email "rgaubert@nvidia.com"
    - git config --global user.name "Renaud Gaubert"


    - helm init --client-only
    - >
      if [[ "${CI_COMMIT_TAG}" != "${CI_COMMIT_SHA}" ]]; then # this is a tag
          helm package --set nvidia.operator.repository="nvcr.io/nvidia" \
                       --set nvidia.driver.repository="nvcr.io/nvidia" \
                       --set nvidia.toolkit.repository="nvcr.io/nvidia" \
                       --set nvidia.devicePlugin.repository="nvcr.io/nvidia" \
                       deploymnets/gpu-operator
      else
          helm package deployments/gpu-operator
      fi

    - git checkout .
    - git fetch origin gh-pages && git checkout gh-pages
    - helm repo index . --url https://nvidia.github.io/gpu-operator
    - git add ./*.tgz index.yaml
    - git commit -m "Release version ${CI_COMMIT_TAG}"

    # CI_REPOSITORY_URL=https://gitlab-ci-token:xxxxxxxxxxxxxxxxxxxx@example.com/gitlab-examples/ci-debug-trace.git
    # should be git@example.com:/gitlab-examples/ci-debug-trace.git
    - PUSH_REPO=$(echo "${CI_REPOSITORY_URL}" | sed -e "s|.*@\(.*\)|git@\1|" -e "s|/|:/|" )
    - git remote set-url --push origin "${PUSH_REPO}"
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
    - git push origin gh-pages
