services:
  - docker:stable-dind

variables:
  IMAGE: $CI_REGISTRY_IMAGE:latest
  BUILDER: $CI_REGISTRY_IMAGE:builder

stages:
  - gitlab
  - unit
  - build

gitlab-builder:
  image: docker:stable
  stage: gitlab
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $BUILDER -f ./docker/builder.Dockerfile
    - make devel BUILDER=$BUILDER
    - docker push $BUILDER

unit-tests:
  stage: unit
  image: $BUILDER_IMAGE
  script:
    - make verify


build-image:
  stage: build
  image: docker:stable
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - make image IMAGE=$(IMAGE_NAME)
    - docker push $IMAGE_NAME
