apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nvidia-container-toolkit
  namespace: gpu-operator-resources
  labels:
    app.kubernetes.io/component: "container-toolkit"
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged
