apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nvidia-container-toolkit
  namespace: gpu-operator-resources
  labels:
    app.kubernetes.io/component: "container-toolkit"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nvidia-container-toolkit
  namespace: gpu-operator-resources
subjects:
- kind: ServiceAccount
  name: nvidia-container-toolkit
  namespace: gpu-operator-resources
userNames:
- system:serviceaccount:gpu-operator:nvidia-container-toolkit
