apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nvidia-dcgm-exporter
  namespace: gpu-operator-resources
  labels:
    app.kubernetes.io/component: "dcgm-exporter"
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
