apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nvidia-dcgm-exporter
  namespace: gpu-operator-resources
spec:
  endpoints:
  - port: gpu-metrics
    path: "/gpu/metrics"
  jobLabel: app
  namespaceSelector:
    matchNames:
    - gpu-operator-resources
  selector:
    matchLabels:
     app: nvidia-dcgm-exporter
