apiVersion: apps/v1
kind: Deployment
metadata:
  name: special-resource-operator
  namespace: gpu-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: special-resource-operator
  template:
    metadata:
      labels:
        name: special-resource-operator
      annotations:
        openshift.io/scc: restricted-readonly
    spec:
      serviceAccount: special-resource-operator
      serviceAccountName: special-resource-operator
      # readOnlyRootFilesystem: true

      containers:
      - name: special-resource-operator
        image: {{ .Values.nvidia.operator.repository }}/{{ .Values.nvidia.operator.image }}:{{ .Values.nvidia.operator.tag }}
        imagePullPolicy: IfNotPresent
        command: ["gpu-operator"]

        env:
        - name: NVIDIA_DRIVER
          valueFrom:
            configMapKeyRef:
              name: operator-config
              key: driver
        - name: NVIDIA_TOOLKIT_DEFAULT_RUNTIME
          value: "{{ .Values.nvidia.operator.defaultRuntime }}"
        - name: NVIDIA_TOOLKIT
          valueFrom:
            configMapKeyRef:
              name: operator-config
              key: toolkit
        - name: NVIDIA_DEVICE_PLUGIN
          valueFrom:
            configMapKeyRef:
              name: operator-config
              key: devicePlugin
        - name: KUBE_UNSUPPORTED_FLAVOR
          valueFrom:
            configMapKeyRef:
              name: operator-config
              key: unsupported
        - name: WATCH_NAMESPACE
          value: ""
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "special-resource-operator"

        readinessProbe:
          exec:
            command: ["stat", "/tmp/operator-sdk-ready"]
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
        ports:
        - containerPort: 60000
          name: metrics

      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Equal"
          value: ""
          effect: "NoSchedule"
