apiVersion: nvidia.com/v1
kind: ClusterPolicy
metadata:
  name: cluster-policy
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/component: "gpu-operator"
    {{ $.Release.labels }}
spec:
  operator:
    defaultRuntime: "{{ .Values.operator.defaultRuntime }}"
  driver:
    repository: "{{ .Values.driver.repository }}"
    image: "{{ .Values.driver.image }}"
    version: "{{ .Values.driver.version }}"
  toolkit:
    repository: "{{ .Values.toolkit.repository }}"
    image: "{{ .Values.toolkit.image }}"
    version: "{{ .Values.toolkit.version }}"
  devicePlugin:
    repository: "{{ .Values.devicePlugin.repository }}"
    image: "{{ .Values.devicePlugin.image }}"
    version: "{{ .Values.devicePlugin.version }}"
  dcgmExporter:
    repository: "{{ .Values.dcgmExporter.repository }}"
    image: "{{ .Values.dcgmExporter.image }}"
    version: "{{ .Values.dcgmExporter.version }}"
