apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nvidia-device-plugin-validation
  name: nvidia-device-plugin-validation
  namespace: gpu-operator-resources
spec:
  tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule
  serviceAccount: nvidia-device-plugin
  serviceAccountName: nvidia-device-plugin
  readOnlyRootFilesystem: true
  restartPolicy: OnFailure
  containers:
    - name: cuda-vector-add
      image: "nvidia/cuda:10.2-devel-ubi8"
      command: ["/bin/bash"]
      args: ["-c","dnf update -y && dnf install -y git make && cd /usr/local/cuda-10.2/ && git clone https://github.com/NVIDIA/cuda-samples.git && cd cuda-samples/ && make -k ; cd Samples/vectorAdd_nvrtc && ./vectorAdd_nvrtc"]
      env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: all
      securityContext:
        allowPrivilegeEscalation: false
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPU
